
    create table categoria (
        id integer generated by default as identity,
        descrizione varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table composizione (
        id integer generated by default as identity,
        id_ingrediente integer,
        id_prodotto integer,
        quantita integer,
        primary key (id)
    );

    create table ingredienti (
        id integer generated by default as identity,
        is_gluten_free boolean,
        is_lactose_free boolean,
        is_vegan boolean,
        prezzo_restock float4,
        sovraprezzo_aggiunta float4,
        colore varchar(255),
        descrizione varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table operazione_magazzino (
        data date,
        delta_quantita float4,
        id integer generated by default as identity,
        id_ingrediente integer,
        causale varchar(255),
        primary key (id)
    );

    create table ordine (
        data_creazione date,
        id integer generated by default as identity,
        id_utente integer,
        prezzo_totale numeric(38,2),
        indirizzo_destinazione varchar(255),
        status varchar(255) check ((status in ('IN_PREPARAZIONE','IN_TRANSITO','COMPLETATO'))),
        primary key (id)
    );

    create table ordine_prodotto (
        id integer generated by default as identity,
        id_ordine integer,
        prezzo numeric(38,2),
        prodotto_id integer unique,
        quantita integer,
        primary key (id)
    );

    create table prodotto (
        id integer generated by default as identity,
        descrizione varchar(255),
        img_url varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table prodotto_categorie (
        categoria_id integer not null,
        prodotto_id integer not null
    );

    create table utente (
        credito numeric(38,2),
        id integer generated by default as identity,
        ruolo smallint check ((ruolo between 0 and 1)),
        email varchar(255),
        indirizzo varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

    alter table if exists composizione 
       add constraint fk_composizione_ingrediente 
       foreign key (id_ingrediente) 
       references ingredienti;

    alter table if exists composizione 
       add constraint fk_composizione_prodotto 
       foreign key (id_prodotto) 
       references prodotto;

    alter table if exists operazione_magazzino 
       add constraint fk_operazionemagazzino_ingrediente 
       foreign key (id_ingrediente) 
       references ingredienti;

    alter table if exists ordine 
       add constraint fk_ordine_utente 
       foreign key (id_utente) 
       references utente;

    alter table if exists ordine_prodotto 
       add constraint fk_ordine_prodotto 
       foreign key (id_ordine) 
       references ordine;

    alter table if exists ordine_prodotto 
       add constraint fk_prodotto_ordine 
       foreign key (prodotto_id) 
       references prodotto;

    alter table if exists prodotto_categorie 
       add constraint FKd9yh6jm4nqb4baamuihqw64fl 
       foreign key (categoria_id) 
       references categoria;

    alter table if exists prodotto_categorie 
       add constraint FKd0smw11vyyv097ni9s132wka4 
       foreign key (prodotto_id) 
       references prodotto;
