
    create table allergeni (
        id integer generated by default as identity,
        nome varchar(255),
        url_icons varchar(255),
        primary key (id)
    );

    create table categoria_ingrediente (
        id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table composizione (
        id integer generated by default as identity,
        id_ingrediente integer,
        id_prodotto integer,
        quantita integer,
        primary key (id)
    );

    create table ingrediente_allergeni (
        allergene_id integer not null,
        ingrediente_id integer not null,
        primary key (allergene_id, ingrediente_id)
    );

    create table ingredienti (
        categoria_id integer,
        id integer generated by default as identity,
        prezzo_restock float4,
        sovraprezzo_aggiunta float4,
        quantita_stock bigint,
        colore varchar(255),
        descrizione varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table key_values (
        key_for_storage varchar(1024) not null,
        values_stored jsonb,
        primary key (key_for_storage)
    );

    create table operazione_magazzino (
        data date,
        delta_quantita float4,
        id integer generated by default as identity,
        id_ingrediente integer,
        causale varchar(255),
        primary key (id)
    );

    create table ordine (
        data_creazione date,
        id integer generated by default as identity,
        id_utente integer,
        prezzo_totale numeric(38,2),
        indirizzo_destinazione varchar(255),
        status varchar(255) check ((status in ('IN_PREPARAZIONE','IN_TRANSITO','COMPLETATO'))),
        primary key (id)
    );

    create table ordine_prodotto (
        id integer generated by default as identity,
        id_ordine integer,
        prezzo numeric(38,2),
        prodotto_id integer unique,
        quantita integer,
        primary key (id)
    );

    create table prodotto (
        id integer generated by default as identity,
        descrizione varchar(255),
        img_url varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table prodotto_promozione (
        prodotto_id integer not null,
        promozione_id integer not null
    );

    create table prodotto_tag (
        prodotto_id integer not null,
        tag_id integer not null
    );

    create table promozione (
        id integer generated by default as identity,
        is_active boolean,
        sconto float4,
        primary key (id)
    );

    create table tag_prodotto (
        id integer generated by default as identity,
        descrizione varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table utente (
        credito numeric(38,2),
        id integer generated by default as identity,
        email varchar(255) not null,
        indirizzo varchar(255),
        password varchar(255) not null,
        ruolo varchar(255) check ((ruolo in ('UTENTE','ADMIN'))),
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists composizione 
       add constraint fk_composizione_ingrediente 
       foreign key (id_ingrediente) 
       references ingredienti;

    alter table if exists composizione 
       add constraint fk_composizione_prodotto 
       foreign key (id_prodotto) 
       references prodotto;

    alter table if exists ingrediente_allergeni 
       add constraint FKt5tc4qlat5k66h0qi7qc62v8k 
       foreign key (allergene_id) 
       references allergeni;

    alter table if exists ingrediente_allergeni 
       add constraint FKl7ia407ebhgbgwcvq25fv72y0 
       foreign key (ingrediente_id) 
       references ingredienti;

    alter table if exists ingredienti 
       add constraint FKdrp3f0eh035acny2845s84jud 
       foreign key (categoria_id) 
       references categoria_ingrediente;

    alter table if exists operazione_magazzino 
       add constraint fk_operazionemagazzino_ingrediente 
       foreign key (id_ingrediente) 
       references ingredienti;

    alter table if exists ordine 
       add constraint fk_ordine_utente 
       foreign key (id_utente) 
       references utente;

    alter table if exists ordine_prodotto 
       add constraint fk_ordine_prodotto 
       foreign key (id_ordine) 
       references ordine;

    alter table if exists ordine_prodotto 
       add constraint fk_prodotto_ordine 
       foreign key (prodotto_id) 
       references prodotto;

    alter table if exists prodotto_promozione 
       add constraint FKqofkxk4to9kr92tqxnssq1tlj 
       foreign key (promozione_id) 
       references promozione;

    alter table if exists prodotto_promozione 
       add constraint FK7rwhver15f0r79mi4fii21ywx 
       foreign key (prodotto_id) 
       references prodotto;

    alter table if exists prodotto_tag 
       add constraint FKhjbnv15gqiaap7euksgmmb10t 
       foreign key (tag_id) 
       references tag_prodotto;

    alter table if exists prodotto_tag 
       add constraint FK4c4df3aai5yp50tttntjgeq7k 
       foreign key (prodotto_id) 
       references prodotto;
